/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Score;

import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author denia
 */
public class VScore extends javax.swing.JFrame {

    /**
     * Creates new form VScore
     */
    public VScore() {
        initComponents();
        tabla2.setVisible(false);
        labelMulti.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPlayer1 = new javax.swing.JLabel();
        jBack = new javax.swing.JButton();
        jBPlayer = new javax.swing.JButton();
        jBMulti = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla2 = new javax.swing.JTable();
        labelMulti = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(475, 420));
        setPreferredSize(new java.awt.Dimension(510, 440));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPlayer1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPlayer1.setText("Puntuación: Un jugador");
        getContentPane().add(jPlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 256, 49));

        jBack.setText("Back");
        jBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackActionPerformed(evt);
            }
        });
        getContentPane().add(jBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 359, -1, -1));

        jBPlayer.setText("1 Jugador");
        jBPlayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBPlayerMouseClicked(evt);
            }
        });
        getContentPane().add(jBPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        jBMulti.setText("Mas Jugadores");
        jBMulti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBMultiMouseClicked(evt);
            }
        });
        jBMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMultiActionPerformed(evt);
            }
        });
        getContentPane().add(jBMulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, -1, -1));

        tabla1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Resultado", "Tiempo", "Puntuación", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla1);
        if (tabla1.getColumnModel().getColumnCount() > 0) {
            tabla1.getColumnModel().getColumn(0).setResizable(false);
            tabla1.getColumnModel().getColumn(1).setResizable(false);
            tabla1.getColumnModel().getColumn(2).setResizable(false);
            tabla1.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 390, 260));

        tabla2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Ganador", "Puntuación", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabla2);
        if (tabla2.getColumnModel().getColumnCount() > 0) {
            tabla2.getColumnModel().getColumn(0).setResizable(false);
            tabla2.getColumnModel().getColumn(1).setResizable(false);
            tabla2.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 390, 260));

        labelMulti.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelMulti.setText("Puntuación: Multijugador");
        getContentPane().add(labelMulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jBackActionPerformed

    private void jBPlayerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPlayerMouseClicked
        // TODO add your handling code here:
        tabla1.setVisible(true);
        jPlayer1.setVisible(true);
        tabla2.setVisible(false);
        labelMulti.setVisible(false);
    }//GEN-LAST:event_jBPlayerMouseClicked

    private void jBMultiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBMultiMouseClicked
        // TODO add your handling code here:
        tabla1.setVisible(false);
        jPlayer1.setVisible(false);
        tabla2.setVisible(true);
        labelMulti.setVisible(true);
        
        //Conexion
        
        try {
            Class.forName("org.sqlite.JDBC");
            URL path = getClass().getResource("/resource/localdbog.db");
            String url = "jdbc:sqlite:" + path.getFile().substring(1);
            Connection con = DriverManager.getConnection(url);
            
            Statement st = con.createStatement();
            String sql = "SELECT * FROM ScoreMulti";
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                String winner = rs.getString("Winner");
                String scorem = String.valueOf(rs.getInt("ScoreM"));
                String datem = rs.getString("Date");
                
                String tbData[] = {winner, scorem, datem};
                DefaultTableModel tblMode1 = (DefaultTableModel)tabla2.getModel();
                tblMode1.addRow(tbData);
                
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jBMultiMouseClicked

    private void jBMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMultiActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jBMultiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VScore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBMulti;
    private javax.swing.JButton jBPlayer;
    private javax.swing.JButton jBack;
    private javax.swing.JLabel jPlayer1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelMulti;
    private javax.swing.JTable tabla1;
    private javax.swing.JTable tabla2;
    // End of variables declaration//GEN-END:variables
}
