/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Score;

import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import quizzer.VPrincipal;

/**
 *
 * @author denia
 */
public class VScore extends javax.swing.JFrame {

    /**
     * Creates new form VScore
     */
    public VScore() {
        initComponents();
        jScrollPane3.setVisible(false);
        //tablaMulti.setVisible(false);
        labelMulti.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSingle = new javax.swing.JLabel();
        jBack = new javax.swing.JButton();
        jBPlayer = new javax.swing.JButton();
        jBMulti = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaMulti = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaSingle = new javax.swing.JTable();
        labelMulti = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(475, 420));
        setPreferredSize(new java.awt.Dimension(510, 440));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelSingle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelSingle.setText("Puntuación: Un jugador");
        getContentPane().add(labelSingle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 256, 49));

        jBack.setText("Back");
        jBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackActionPerformed(evt);
            }
        });
        getContentPane().add(jBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 359, -1, -1));

        jBPlayer.setText("1 Jugador");
        jBPlayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBPlayerMouseClicked(evt);
            }
        });
        jBPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPlayerActionPerformed(evt);
            }
        });
        getContentPane().add(jBPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        jBMulti.setText("Mas Jugadores");
        jBMulti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBMultiMouseClicked(evt);
            }
        });
        jBMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMultiActionPerformed(evt);
            }
        });
        getContentPane().add(jBMulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, -1, -1));

        tablaMulti.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tablaMulti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ganador", "Puntuación", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaMulti);
        if (tablaMulti.getColumnModel().getColumnCount() > 0) {
            tablaMulti.getColumnModel().getColumn(0).setResizable(false);
            tablaMulti.getColumnModel().getColumn(1).setResizable(false);
            tablaMulti.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 390, 260));

        tablaSingle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tablaSingle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Resultado", "Tiempo", "Puntuación", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaSingle);
        if (tablaSingle.getColumnModel().getColumnCount() > 0) {
            tablaSingle.getColumnModel().getColumn(0).setResizable(false);
            tablaSingle.getColumnModel().getColumn(1).setResizable(false);
            tablaSingle.getColumnModel().getColumn(2).setResizable(false);
            tablaSingle.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 390, 260));

        labelMulti.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelMulti.setText("Puntuación: Multijugador");
        getContentPane().add(labelMulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackActionPerformed
        // TODO add your handling code here:
        //VPrincipal vp = new VPrincipal();
        
        
    }//GEN-LAST:event_jBackActionPerformed

    private void jBPlayerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPlayerMouseClicked
        // holis
    }//GEN-LAST:event_jBPlayerMouseClicked

    private void jBMultiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBMultiMouseClicked
        //aqui no hay nada xd
    }//GEN-LAST:event_jBMultiMouseClicked

    private void jBMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMultiActionPerformed
        // TODO add your handling code here:
        jScrollPane3.setVisible(true);
        jScrollPane2.setVisible(false);
        tablaMulti.removeAll();
        tablaSingle.removeAll();
        //tablaSingle.setVisible(false);
        labelSingle.setVisible(false);
        //tablaMulti.setVisible(true);
        labelMulti.setVisible(true);
        
        //Conexion
        
        Connection con = null;
        Statement st = null;
        
        try {
            Class.forName("org.sqlite.JDBC");
            URL path = getClass().getResource("/resource/localdbog.db");
            String url = "jdbc:sqlite:" + path.getFile().substring(1);
            con = DriverManager.getConnection(url);
            con.setAutoCommit(false);
            
            st = con.createStatement();
            String sql = "SELECT * FROM ScoreMulti;";
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                String winner = rs.getString("Winner");
                String scorem = String.valueOf(rs.getInt("ScoreM"));
                String datem = rs.getString("Date");
                
                String tbData[] = {winner, scorem, datem};
                DefaultTableModel tblModel = (DefaultTableModel)tablaMulti.getModel();
                tblModel.addRow(tbData);
                
            }
            rs.close();
            st.close();
            con.close();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        
    }//GEN-LAST:event_jBMultiActionPerformed

    private void jBPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPlayerActionPerformed
        // TODO add your handling code here:
        jScrollPane3.setVisible(false);
        jScrollPane2.setVisible(true);
        //tablaSingle.setVisible(true);
        labelSingle.setVisible(true);
        tablaMulti.removeAll();
        tablaSingle.removeAll();
        //tablaMulti.setVisible(false);
        labelMulti.setVisible(false);
        
        //Conexion
        
        Connection con = null;
        Statement st = null;
        
        try {
            Class.forName("org.sqlite.JDBC");
            URL path = getClass().getResource("/resource/localdbog.db");
            String url = "jdbc:sqlite:" + path.getFile().substring(1);
            con = DriverManager.getConnection(url);
            con.setAutoCommit(false);
            
            st = con.createStatement();
            String sql = "SELECT * FROM ScoreSingle;";
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                String status = rs.getString("Outcome");
                String duration = rs.getString("Duration");
                String score = String.valueOf(rs.getInt("Score"));
                String date = rs.getString("Date");
                
                String tbData[] = {status, duration, score,date};
                DefaultTableModel tblModel = (DefaultTableModel)tablaSingle.getModel();
                tblModel.addRow(tbData);
                
            }
            rs.close();
            st.close();
            con.close();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        
    }//GEN-LAST:event_jBPlayerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VScore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBMulti;
    private javax.swing.JButton jBPlayer;
    private javax.swing.JButton jBack;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelMulti;
    private javax.swing.JLabel labelSingle;
    private javax.swing.JTable tablaMulti;
    private javax.swing.JTable tablaSingle;
    // End of variables declaration//GEN-END:variables
}
