/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizzer;

import java.awt.Color;
import java.awt.GridLayout;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.LinkedList;
import java.util.Map;
import java.util.Queue;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.border.LineBorder;
import objetos.Celda;
import objetos.Jugador;

/**
 *
 * @author Benjimon41
 */
public class TableroVersion0v2 extends javax.swing.JFrame {

    Celda[][] grid;
    Map<Integer, int[]> hash = new HashMap<>();
    JLayeredPane lp = new JLayeredPane();
    int n;
    public TableroVersion0v2() throws IOException {
        initComponents();
        n = 9;
        grid= new Celda[(int)Math.sqrt(n)][(int)Math.sqrt(n)];
        //frame
        setDefaultCloseOperation(TableroVersion0.EXIT_ON_CLOSE);
        this.setSize(1000, 750);
        //layered
        switch(n)
        {
            case 9:
                lp.setBounds(150, 5, 550, 250);
            break;
            
            case 16:
                lp.setBounds(150, 5, 550, 250);
            break;
            
            case 49:
                lp.setBounds(150, 5, 550, 250);
            break;
            
            case 64:
                lp.setBounds(150, 5, 550, 250);
            break;
            
        }
        lp.setOpaque(true);
        lp.setBackground(Color.yellow);
        this.add(lp);
        //tablero
        this.dibujarTabla(n);
        this.cargarValores(n);
        this.cargarJugadores();
    }

    public void dibujarTabla(int n) {

        for (int i = 0; i < Math.sqrt(n); i++) {
            for (int j = 0; j < Math.sqrt(n); j++) {
                Celda c = new Celda(new JLabel(), 0);
                c.cell.setBounds(j * 80,i * 60,80,60);
                c.cell.setBorder(new LineBorder(Color.BLACK));
                grid[i][j] = c;
                lp.add(c.cell,Integer.valueOf(0));
                //jPanel1.add(c.cell);
            }
        }
    }

    public void cargarValores(int n) throws IOException {
        int value = 1;

        int minCol = (int) (Math.sqrt(n) - 1);
        int minRow = (int) (Math.sqrt(n) - 1);

        int maxCol = 0;
        int maxRow = 0;

        while (value <= n) {
            for (int i = minCol; i >= maxCol; i--) {
                grid[minRow][i].setValor(value);
                this.direccion(value, grid[minRow][i].getPanelPosicion());
                if (value == 1) {
                    grid[minRow][i].asignarImagen(0);
                }
                if (value == n) {
                    grid[minRow][i].asignarImagen(1);
                }
                value++;
            }

            for (int i = minRow - 1; i >= maxRow; i--) {
                grid[i][maxCol].setValor(value);
                this.direccion(value, grid[i][maxCol].getPanelPosicion());
                if (value == n) {
                    grid[i][maxCol].asignarImagen(1);
                }
                value++;
            }

            for (int i = maxCol + 1; i <= minCol; i++) {
                grid[maxRow][i].setValor(value);
                this.direccion(value, grid[maxRow][i].getPanelPosicion());
                if (value == n) {
                    grid[maxRow][i].asignarImagen(1);
                }
                value++;
            }

            for (int i = maxRow + 1; i <= minRow - 1; i++) {
                grid[i][minCol].setValor(value);
                this.direccion(value, grid[i][minCol].getPanelPosicion());
                if (value == n) {
                    grid[i][minCol].asignarImagen(1);
                }
                value++;
            }

            minCol--;

            minRow--;

            maxCol++;

            maxRow++;
        }
    }

    public void direccion(int valor, int[] posicion) {
        hash.put(valor, posicion);
    }
    
    public void cargarJugadores() throws IOException {
        //for (int i : this.hash.get(1)) {}
        Jugador p = new Jugador("benji", 0);
        Celda cP1 = new Celda(new JLabel(), 0, p);
        cP1.asignarImagen(2);
        cP1.cell.setBounds(hash.get(1)[0],hash.get(1)[1],40,40);
        lp.add(cP1.cell,Integer.valueOf(1));
        // this.jPanel1.add(cP1.cell);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableroVersion0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableroVersion0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableroVersion0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableroVersion0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TableroVersion0v2().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(TableroVersion0v2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
