/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizzer;

import java.awt.Color;
import java.awt.GridLayout;
import java.io.IOException;
import java.util.LinkedList;
import java.util.Queue;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.border.LineBorder;
import objetos.Celda;

/**
 *
 * @author Benjimon41
 */
public class TableroVersion0 extends javax.swing.JFrame {
Celda[][] grid= new Celda[3][3];
    public TableroVersion0() throws IOException {
        initComponents();
        setDefaultCloseOperation(TableroVersion0.EXIT_ON_CLOSE);
        setBounds(100, 100, 500, 500);
        //this.jPanel1.setVisible(false);
        this.dibujarTabla(9);
        this.cargarValores(9);
    }
    public void dibujarTabla(int n){
        
        for (int i = 0; i < Math.sqrt(n); i++) {
            for (int j = 0; j < Math.sqrt(n); j++) {
                Celda c = new Celda(new JLabel(), 0);
                c.asignarPosicionPanel(j*40, i*40);
                c.cell.setSize(40,40);
                c.cell.setBorder(new LineBorder(Color.BLACK));
                c.cell.setOpaque(true);
                grid[i][j]=c;
                jPanel1.add(c.cell);
            }
        }
    }
    
    public void cargarValores(int n) throws IOException{
        int value = 1;
         
        int minCol = (int) (Math.sqrt(n)-1);
        int minRow = (int) (Math.sqrt(n)-1);
         
        int maxCol = 0;
        int maxRow = 0;
         
        while (value <= n)
        {
            for (int i = minCol; i >= maxCol; i--)
            {
                grid[minRow][i].asignarValor(value);
                if(value==1)grid[minRow][i].asignarImagen(0);
                if(value==n)grid[minRow][i].asignarImagen(1);
                value++;
            }
            
            for (int i = minRow-1; i >= maxRow; i--) 
            { 
                grid[i][maxCol].asignarValor(value);
                if(value==n)grid[minRow][i].asignarImagen(1);
                value++; 
            }
           
            for (int i = maxCol+1; i <= minCol; i++)
            {
                grid[maxRow][i].asignarValor(value);
                if(value==n)grid[minRow][i].asignarImagen(1);
                value++;
            }
           
            for (int i = maxRow+1; i <= minRow-1; i++) 
            {
                grid[i][minCol].asignarValor(value);
                if(value==n)grid[minRow][i].asignarImagen(1);
                value++;
            }
            
            

             
            minCol--;
             
            minRow--;
             
            maxCol++;
             
            maxRow++;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableroVersion0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableroVersion0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableroVersion0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableroVersion0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TableroVersion0().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(TableroVersion0.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
