
package quizzer;

import java.awt.Checkbox;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import objetos.Jugador;
import objetos.Pregunta;

/**
 *
 * @author denia
 */
public class VPersonalizacion extends javax.swing.JFrame {

    Connection con = null;
    int categoriasSeleccionadas=0;
    int celdas;
    int tipo;
    ArrayList<String> listaCatego=new ArrayList<>();
    ArrayList<Jugador> players = new ArrayList<>();
    ArrayList<String> categoriasJugar = new ArrayList<>();
    ArrayList<objetos.Pregunta> preguntas;
    Jugador j1;
    Jugador j2;
    Jugador j3;
    String queryQuestL = "SELECT Pregunta,Categoria,RespuestaCorrecta,RespuestaIncorrecta1,RespuestaIncorrecta2 from Pregunta;";
    
    public VPersonalizacion(Connection con) {
        initComponents();
        
        this.con = con;
        
        setLocationRelativeTo(null);
        LabelNombrej1.setVisible(false);
        LabelNombrej2.setVisible(false);
        LabelNombrej3.setVisible(false);
        nombreJ1.setVisible(false);
        nombreJ2.setVisible(false);
        nombreJ3.setVisible(false);
        player1.setVisible(false);
        player2.setVisible(false);
        player3.setVisible(false);
       
        this.listaCatego = new ArrayList<String>();
        this.categoriasJugar = new ArrayList<String>();
        this.preguntas = new ArrayList<Pregunta>();
        
        
        datos();
        cargarCategorias();
       
    }

    private VPersonalizacion() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numJugadores = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboBoxCasillas = new javax.swing.JComboBox<>();
        comboBoxPreguntas = new javax.swing.JComboBox<>();
        start = new javax.swing.JButton();
        RadioButton1j = new javax.swing.JRadioButton();
        RadioButton2j = new javax.swing.JRadioButton();
        RadioButton3j = new javax.swing.JRadioButton();
        LabelNombrej1 = new javax.swing.JLabel();
        LabelNombrej2 = new javax.swing.JLabel();
        LabelNombrej3 = new javax.swing.JLabel();
        nombreJ3 = new javax.swing.JTextField();
        nombreJ1 = new javax.swing.JTextField();
        nombreJ2 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        player1 = new javax.swing.JLabel();
        player2 = new javax.swing.JLabel();
        player3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(687, 440));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Número de jugadores:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Seleccione las categorias (max. 6):");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Duración por pregunta:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Seleccione el número de casillas:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Personalice la partida");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 11, -1, -1));

        comboBoxCasillas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "9", "16", "49", "64" }));
        comboBoxCasillas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCasillasActionPerformed(evt);
            }
        });
        getContentPane().add(comboBoxCasillas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 91, -1));

        comboBoxPreguntas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "0:10", "0:20", "0:30", "0:40", "0:50", "1:00", "1:30", "2:00" }));
        getContentPane().add(comboBoxPreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 91, -1));

        start.setText("Iniciar");
        start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startMouseClicked(evt);
            }
        });
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        getContentPane().add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, 80, 30));

        numJugadores.add(RadioButton1j);
        RadioButton1j.setText("1 jugador");
        RadioButton1j.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton1jActionPerformed(evt);
            }
        });
        getContentPane().add(RadioButton1j, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        numJugadores.add(RadioButton2j);
        RadioButton2j.setText("2 jugadores");
        RadioButton2j.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton2jActionPerformed(evt);
            }
        });
        getContentPane().add(RadioButton2j, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        numJugadores.add(RadioButton3j);
        RadioButton3j.setText("3 jugadores");
        RadioButton3j.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton3jActionPerformed(evt);
            }
        });
        getContentPane().add(RadioButton3j, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        LabelNombrej1.setText("Nombre del jugador 1:");
        getContentPane().add(LabelNombrej1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        LabelNombrej2.setText("Nombre del jugador 2:");
        getContentPane().add(LabelNombrej2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        LabelNombrej3.setText("Nombre del jugador 3:");
        getContentPane().add(LabelNombrej3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        nombreJ3.setText("nombre");
        getContentPane().add(nombreJ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 100, -1));

        nombreJ1.setText("nombre");
        nombreJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreJ1ActionPerformed(evt);
            }
        });
        getContentPane().add(nombreJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 100, -1));

        nombreJ2.setText("nombre");
        getContentPane().add(nombreJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 100, -1));

        jCheckBox1.setText("jCheckBox2");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jCheckBox2.setText("jCheckBox1");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jCheckBox3.setText("jCheckBox3");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        jCheckBox4.setText("jCheckBox4");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        jCheckBox5.setText("jCheckBox5");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        jCheckBox6.setText("jCheckBox6");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        jCheckBox7.setText("jCheckBox7");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, -1, -1));

        jCheckBox8.setText("jCheckBox8");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, -1));

        jCheckBox9.setText("jCheckBox9");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, -1, -1));

        jCheckBox10.setText("jCheckBox10");
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, -1, -1));

        player1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/player1.png"))); // NOI18N
        getContentPane().add(player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, -1));

        player2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/player2.png"))); // NOI18N
        getContentPane().add(player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, -1, -1));

        player3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/player3.png"))); // NOI18N
        getContentPane().add(player3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxCasillasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCasillasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxCasillasActionPerformed

    private void RadioButton1jActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton1jActionPerformed
        // TODO add your handling code here:
        players.clear();
        LabelNombrej1.setVisible(true);
        nombreJ1.setVisible(true);
        LabelNombrej2.setVisible(false);
        nombreJ2.setVisible(false);
        LabelNombrej3.setVisible(false);
        nombreJ3.setVisible(false);
        player1.setVisible(true);
        player2.setVisible(false);
        player3.setVisible(false);
        /*if (RadioButton1j.isSelected()==true){
            String name = nombreJ1.getText();
            j1 = new Jugador(name, 0, 1);
            players.add(j1);
        }else{
            nombreJ2.setText("");
            nombreJ3.setText("");
            
        }*/
        tipo = 0;
    }//GEN-LAST:event_RadioButton1jActionPerformed

    private void RadioButton2jActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton2jActionPerformed
        // TODO add your handling code here:
        players.clear();
        LabelNombrej1.setVisible(true);
        nombreJ1.setVisible(true);
        LabelNombrej2.setVisible(true);
        nombreJ2.setVisible(true);
        LabelNombrej3.setVisible(false);
        nombreJ3.setVisible(false);
        player1.setVisible(true);
        player2.setVisible(true);
        player3.setVisible(false);
        
        /*if (RadioButton2j.isSelected()==true){
            String name1 = nombreJ1.getText();
            String name2 = nombreJ2.getText();
            j1 = new Jugador(name1, 0, 1);
            j2 = new Jugador(name2, 0, 2);
            players.add(j1);
            players.add(j2);
        }else{
            nombreJ3.setText("");
        }*/
        tipo=1;
    }//GEN-LAST:event_RadioButton2jActionPerformed

    private void RadioButton3jActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton3jActionPerformed
        // TODO add your handling code here:
        players.clear();
        LabelNombrej1.setVisible(true);
        nombreJ1.setVisible(true);
        LabelNombrej2.setVisible(true);
        nombreJ2.setVisible(true);
        LabelNombrej3.setVisible(true);
        nombreJ3.setVisible(true);
        player1.setVisible(true);
        player2.setVisible(true);
        player3.setVisible(true);
        
        /*if (RadioButton2j.isSelected()==true){
            String name1 = nombreJ1.getText();
            String name2 = nombreJ2.getText();
            String name3 = nombreJ3.getText();
            j1 = new Jugador(name1, 0, 1);
            j2 = new Jugador(name2, 0, 2);
            j3 = new Jugador(name3, 0, 3);
            players.add(j1);
            players.add(j2);
            players.add(j3);
        }*/
        tipo=1;
    }//GEN-LAST:event_RadioButton3jActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
       /* if (categoriasSeleccionadas>6){
            //jLabel6.setText("son mas de 8");
            JOptionPane.showMessageDialog(null, "Tiene mas de 6 categorias seleccionadas, quite algunas");
        }else{
            celdas = comboBoxCasillas.getSelectedIndex();
            VJugar vj = null;
            try{
            vj = new VJugar(celdas,players,tipo,preguntas, categoriasJugar,this.con);
            }catch (IOException ex) {
            Logger.getLogger(VPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        vj.setVisible(true);
        this.setVisible(false);
            //jLabel6.setText("son menos de 8");
        }*/
        
        
    }//GEN-LAST:event_startActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()==true){
            categoriasSeleccionadas= categoriasSeleccionadas+1;
            categoriasJugar.add(jCheckBox1.getText());
            //jCheckBox1.setText("seleccionado");
        }else{
            categoriasSeleccionadas= categoriasSeleccionadas-1;
            categoriasJugar.remove(jCheckBox1.getText());
            //jCheckBox1.setText("no seleccionado");
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox2.isSelected()==true){
            categoriasSeleccionadas= categoriasSeleccionadas+1;
            categoriasJugar.add(jCheckBox2.getText());
            //jCheckBox1.setText("seleccionado");
        }else{
            categoriasSeleccionadas= categoriasSeleccionadas-1;
            categoriasJugar.remove(jCheckBox2.getText());
            //jCheckBox1.setText("no seleccionado");
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox3.isSelected()==true){
            categoriasSeleccionadas= categoriasSeleccionadas+1;
            categoriasJugar.add(jCheckBox3.getText());
            //jCheckBox1.setText("seleccionado");
        }else{
            categoriasSeleccionadas= categoriasSeleccionadas-1;
            categoriasJugar.remove(jCheckBox3.getText());
            //jCheckBox1.setText("no seleccionado");
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox4.isSelected()==true){
            categoriasSeleccionadas= categoriasSeleccionadas+1;
            categoriasJugar.add(jCheckBox4.getText());
            //jCheckBox1.setText("seleccionado");
        }else{
            categoriasSeleccionadas= categoriasSeleccionadas-1;
            categoriasJugar.remove(jCheckBox4.getText());

            //jCheckBox1.setText("no seleccionado");
        }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox5.isSelected()==true){
            categoriasSeleccionadas= categoriasSeleccionadas+1;
            categoriasJugar.add(jCheckBox5.getText());

            //jCheckBox1.setText("seleccionado");
        }else{
            categoriasSeleccionadas= categoriasSeleccionadas-1;
            categoriasJugar.remove(jCheckBox5.getText());
            //jCheckBox1.setText("no seleccionado");
        }
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox6.isSelected()==true){
            categoriasSeleccionadas= categoriasSeleccionadas+1;
            categoriasJugar.add(jCheckBox6.getText());
            //jCheckBox1.setText("seleccionado");
        }else{
            categoriasSeleccionadas= categoriasSeleccionadas-1;
            categoriasJugar.remove(jCheckBox6.getText());
            //jCheckBox1.setText("no seleccionado");
        }
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox7.isSelected()==true){
            categoriasSeleccionadas= categoriasSeleccionadas+1;
            categoriasJugar.add(jCheckBox7.getText());
            //jCheckBox1.setText("seleccionado");
        }else{
            categoriasSeleccionadas= categoriasSeleccionadas-1;
            categoriasJugar.remove(jCheckBox7.getText());
            //jCheckBox1.setText("no seleccionado");
        }
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox8.isSelected()==true){
            categoriasSeleccionadas= categoriasSeleccionadas+1;
            categoriasJugar.add(jCheckBox8.getText());
            //jCheckBox1.setText("seleccionado");
        }else{
            categoriasSeleccionadas= categoriasSeleccionadas-1;
            categoriasJugar.remove(jCheckBox8.getText());
            //jCheckBox1.setText("no seleccionado");
        }
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox9.isSelected()==true){
            categoriasSeleccionadas= categoriasSeleccionadas+1;
            categoriasJugar.add(jCheckBox9.getText());
            //jCheckBox1.setText("seleccionado");
        }else{
            categoriasSeleccionadas= categoriasSeleccionadas-1;
            categoriasJugar.remove(jCheckBox9.getText());
            //jCheckBox1.setText("no seleccionado");
        }
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox10.isSelected()==true){
            categoriasSeleccionadas= categoriasSeleccionadas+1;
            categoriasJugar.add(jCheckBox10.getText());
            //jCheckBox1.setText("seleccionado");
        }else{
            categoriasSeleccionadas= categoriasSeleccionadas-1;
            categoriasJugar.remove(jCheckBox10.getText());
            //jCheckBox1.setText("no seleccionado");
        }
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void nombreJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreJ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreJ1ActionPerformed

    private void startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseClicked
        // TODO add your handling code here:
        if (categoriasSeleccionadas<=6){
            
            if (RadioButton1j.isSelected()==true){
            String name = nombreJ1.getText();
            j1 = new Jugador(name, 0, 1);
            players.add(j1);
            }
            
            if (RadioButton2j.isSelected()==true){
            String name1 = nombreJ1.getText();
            String name2 = nombreJ2.getText();
            j1 = new Jugador(name1, 0, 1);
            j2 = new Jugador(name2, 0, 2);
            players.add(j1);
            players.add(j2);
            }
            if (RadioButton2j.isSelected()==true){
            String name1 = nombreJ1.getText();
            String name2 = nombreJ2.getText();
            String name3 = nombreJ3.getText();
            j1 = new Jugador(name1, 0, 1);
            j2 = new Jugador(name2, 0, 2);
            j3 = new Jugador(name3, 0, 3);
            players.add(j1);
            players.add(j2);
            players.add(j3);
            }
            String valor = (String)comboBoxCasillas.getSelectedItem();
            celdas = Integer.parseInt(valor);
            VJugar vj = null;
            try{
            vj = new VJugar(celdas,players,tipo,preguntas, categoriasJugar,this.con);
            }catch (IOException ex) {
            Logger.getLogger(VPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        vj.setVisible(true);
        this.setVisible(false);
        }
        
        if (categoriasSeleccionadas >6){
            JOptionPane.showMessageDialog(null, "Tiene mas de 6 categorias seleccionadas, quite algunas");
        }
            //jLabel6.setText("son menos de 8");
        
    }//GEN-LAST:event_startMouseClicked

    public void datos(){
        Statement st = null;

        try {
            con.setAutoCommit(false);
            st = con.createStatement();
            String sql = "select distinct Categoria from Pregunta;";
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                String categoria = rs.getString("Categoria");
                this.listaCatego.add(categoria);

            }
            rs.close();
            st.close();
            

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        /*System.out.println("prueba unooo crack");
        for (String cate : listaCatego) {
            System.out.println(cate);
        }*/
        
        
    }
    
    public void cargarCategorias(){
        jCheckBox1.setText(listaCatego.get(0));
        jCheckBox2.setText(listaCatego.get(1));
        jCheckBox3.setText(listaCatego.get(2));
        jCheckBox4.setText(listaCatego.get(3));
        jCheckBox5.setText(listaCatego.get(4));
        jCheckBox6.setText(listaCatego.get(5));
        //jCheckBox7.setText(listaCatego.get(6));
        //jCheckBox8.setText(listaCatego.get(7));
        //jCheckBox9.setText(listaCatego.get(8));
        //jCheckBox10.setText(listaCatego.get(9));
        
        
    }
    
    public void cargarPreguntasCatLocal() throws SQLException {
        Statement st = null;
        con.setAutoCommit(false);
        st = con.createStatement();
        ResultSet rs = st.executeQuery(this.queryQuestL);

        while (rs.next()) {
            String q = rs.getString("Pregunta");
            String c = rs.getString("Categoria");
            String ans = rs.getString("RespuestaCorrecta");
            String wr1 = rs.getString("RespuestaIncorrecta1");
            String wr2 = rs.getString("RespuestaIncorrecta2");
            System.out.println(q + c + ans + wr1 + wr2);
            this.preguntas.add(new Pregunta(q, c, ans, wr1, wr2));
        }
        rs.close();
        st.close();
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPersonalizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPersonalizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPersonalizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPersonalizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPersonalizacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelNombrej1;
    private javax.swing.JLabel LabelNombrej2;
    private javax.swing.JLabel LabelNombrej3;
    private javax.swing.JRadioButton RadioButton1j;
    private javax.swing.JRadioButton RadioButton2j;
    private javax.swing.JRadioButton RadioButton3j;
    private javax.swing.JComboBox<String> comboBoxCasillas;
    private javax.swing.JComboBox<String> comboBoxPreguntas;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nombreJ1;
    private javax.swing.JTextField nombreJ2;
    private javax.swing.JTextField nombreJ3;
    private javax.swing.ButtonGroup numJugadores;
    private javax.swing.JLabel player1;
    private javax.swing.JLabel player2;
    private javax.swing.JLabel player3;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables
}
